### ISSUE TITLE
bug: app.showPage is not a function

### ISSUE THREAD

**Issue by Mirasaki** [sapphiredev/documentation-plugins#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When generating typedoc documentation with the `typedoc-plugin-djs-links` plugin loaded, an empty page is served with the following error in the console:

```
app.showPage is not a function
```

typedoc: `^0.25.13`
typedoc-plugin-djs-links: `^2.2.1`

### Steps To Reproduce

Generate any typedoc documentation using the `typedoc-plugin-djs-links` plugin on the following (latest) versions:
typedoc: `^0.25.13`
typedoc-plugin-djs-links: `^2.2.1`

Remove the plugin from the typedoc config, and the documentation works as expected.

### Expected behavior

The documentation is served as normally, without the error being thrown :)

### Screenshots

![opera_dEeTpzBQqA](https://github.com/sapphiredev/documentation-plugins/assets/57721238/65e6cee9-8aa2-486a-8cb9-61771cddf611)
![Code_qc6gme31Mp](https://github.com/sapphiredev/documentation-plugins/assets/57721238/302eeaf3-f178-4d2b-a751-a94478030bfc)
![Code_A9JZV0znaX](https://github.com/sapphiredev/documentation-plugins/assets/57721238/c098acad-4761-479f-9331-ddd7c2449001)

### Additional context

npm is being used as the package manager for this project.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 8.38 GB / 15.59 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.10.2 - ~/.local/share/pnpm/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
```

**Comment by Mirasaki** [comment]
It's worth noting that the `typedoc` version is inside the peer [dependency version range](https://github.com/sapphiredev/documentation-plugins/blob/86fca203a2562e86284376af189784d315924945/packages/typedoc-djs-links/package.json#L31C1-L33C4)

**Comment by favna** [comment]
uh... we dont call `app.showPage` anywhere in this plugin's code .. this is weird

**Comment by favna** [comment]
Also our plugin is heavily based on [typedoc-plugin-mdn-links](https://github.com/Gerrit0/typedoc-plugin-mdn-links/blob/main/src/index.ts) and their code is basically still the same aside from the other features they implement.

**Comment by Mirasaki** [comment]
I do find myself unable to reproduce this, it's actually limited to just the live environment 🙈 My apologies for creating the issue as I really should have made the repro first.

Thank you for getting back to me!
